# Generated by Django 6.0.2 on 2026-03-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('chef', 'Chef de projet (Ministère)'), ('entreprise', 'Entreprise exécutante'), ('observateur', 'Observateur public')], default='observateur', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.CreateModel(
            name='ChefProjet',
            fields=[
                ('id_chef', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ministere', models.CharField(max_length=150, verbose_name='Nom du ministère')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_projet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef de projet (Ministère)',
                'verbose_name_plural': 'Chefs de projet (Ministères)',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('domaine_activite', models.CharField(max_length=100, verbose_name="Domaine d'activité")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('budget_previsionnel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('a_venir', 'À venir'), ('suspendu', 'Suspendu')], max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='sigep.chefprojet')),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='sigep.entreprise')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
    ]
