# Generated by Django 6.0.2 on 2026-03-19 17:56

import django.db.models.deletion
import sigep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0002_userprofile_role_alter_userprofile_sexe_chefprojet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefprojet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entreprise',
            options={},
        ),
        migrations.AddField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, help_text='Image représentant le projet (obligatoire)', null=True, upload_to=sigep.models.chemin_photo_projet, verbose_name='Photo du projet'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de profil (optionnelle)', null=True, upload_to=sigep.models.chemin_photo_profil, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avenue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id_phase', models.AutoField(primary_key=True, serialize=False)),
                ('nom_phase', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('pourcentage_avancement', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, help_text="Photo illustrant l'avancement de la phase (optionnelle)", null=True, upload_to=sigep.models.chemin_photo_phase, verbose_name='Photo de la phase')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='sigep.projet')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
            },
        ),
    ]
