# Generated by Django 6.0.2 on 2026-03-19 23:36

import django.db.models.deletion
import django.utils.timezone
import sigep.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0003_alter_chefprojet_options_alter_entreprise_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefprojet',
            options={'verbose_name': 'Ministère (Chef de projet)', 'verbose_name_plural': 'Ministères (Chefs de projet)'},
        ),
        migrations.AlterModelOptions(
            name='entreprise',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['date_debut'], 'verbose_name': 'Phase', 'verbose_name_plural': 'Phases'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterField(
            model_name='chefprojet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_projet', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=150, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprise', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='nom_phase',
            field=models.CharField(max_length=100, verbose_name='Nom de la phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo illustrant l'avancement (optionnelle)", null=True, upload_to=sigep.models.chemin_photo_phase, verbose_name='Photo de la phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='pourcentage_avancement',
            field=models.IntegerField(default=0, verbose_name="Pourcentage d'avancement"),
        ),
        migrations.AlterField(
            model_name='phase',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='sigep.projet', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget_previsionnel',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget prévisionnel'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='sigep.chefprojet', verbose_name='Ministère responsable'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin_prevue',
            field=models.DateField(verbose_name='Date de fin prévue'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='sigep.entreprise', verbose_name='Entreprise exécutante'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='photo',
            field=models.ImageField(blank=True, help_text='Image principale du projet (formats: JPG, PNG)', null=True, upload_to=sigep.models.chemin_photo_projet, verbose_name='Photo du projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('a_venir', 'À venir'), ('suspendu', 'Suspendu')], default='a_venir', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=150, verbose_name='Titre du projet'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avenue'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de profil (formats acceptés: JPG, PNG)', null=True, upload_to=sigep.models.chemin_photo_profil, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('chef', 'Chef de projet (Ministère)'), ('entreprise', 'Entreprise exécutante'), ('observateur', 'Observateur public')], default='observateur', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterModelTable(
            name='chefprojet',
            table='chefs_projet',
        ),
        migrations.AlterModelTable(
            name='entreprise',
            table='entreprises',
        ),
        migrations.AlterModelTable(
            name='phase',
            table='phases',
        ),
        migrations.AlterModelTable(
            name='projet',
            table='projets',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='sigep_userprofile',
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date_commentaire', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du commentaire')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='sigep.projet', verbose_name='Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'commentaires',
                'ordering': ['-date_commentaire'],
            },
        ),
        migrations.CreateModel(
            name='SuiviBudget',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('budget_consomme', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget consommé')),
                ('date_mise_a_jour', models.DateField(verbose_name='Date de mise à jour')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_budget', to='sigep.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Suivi budgétaire',
                'verbose_name_plural': 'Suivis budgétaires',
                'db_table': 'suivi_budget',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id_avis', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire (optionnel)')),
                ('date_avis', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'avis")),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='sigep.projet', verbose_name='Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'avis',
                'ordering': ['-date_avis'],
                'unique_together': {('utilisateur', 'projet')},
            },
        ),
        migrations.CreateModel(
            name='ProjetSuivi',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du suivi')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_par', to='sigep.projet', verbose_name='Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_suivis', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Projet suivi',
                'verbose_name_plural': 'Projets suivis',
                'db_table': 'projets_suivis',
                'ordering': ['-date_suivi'],
                'unique_together': {('utilisateur', 'projet')},
            },
        ),
    ]
