# Generated by Django 6.0.2 on 2026-03-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0004_alter_chefprojet_options_alter_entreprise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('a_venir', 'À venir'), ('suspendu', 'Suspendu'), ('annule', 'Annulé')], default='a_venir', max_length=20, verbose_name='Statut'),
        ),
    ]
