# Generated by Django 6.0.2 on 2026-03-21 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0005_alter_projet_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='user',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='entreprises', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs associés'),
        ),
    ]
