# Generated by Django 6.0.2 on 2026-03-21 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0006_remove_entreprise_user_entreprise_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='user',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='representant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprise_representee', to=settings.AUTH_USER_MODEL, verbose_name='Représentant principal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='sigep.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='est_employe',
            field=models.BooleanField(default=False, verbose_name='Est un employé'),
        ),
    ]
