# Generated by Django 6.0.2 on 2026-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0007_remove_entreprise_user_entreprise_representant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='domaine_activite',
            field=models.CharField(default='non_defini', help_text='Ex: Construction, Éducation, Santé, Infrastructures...', max_length=100, verbose_name="Domaine d'activité"),
            preserve_default=False,
        ),
    ]
