# Generated by Django 6.0.2 on 2026-03-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigep', '0008_projet_domaine_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivibudget',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='suivibudget',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='sigep.phase', verbose_name='Phase'),
        ),
    ]
